server:
  port: 80
##数据源1 mysql
spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.48.250:3306/img?characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    servlet:
      multipart:
        max-file-size: 1024MB
        max-request-size: 1024MB

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wpp.pojo  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  reasonable: true
  helperDialect: mysql

TAOTAO_IMAGE_SERVER_URL: http://192.168.25.133/



